# Generated by Django 4.1 on 2024-04-11 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="plate",
            fields=[
                (
                    "title",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("create_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="userInfo",
            fields=[
                (
                    "username",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="用户名",
                    ),
                ),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
                (
                    "gender",
                    models.CharField(
                        choices=[(0, "女"), (1, "男")],
                        max_length=1,
                        null=True,
                        verbose_name="性别",
                    ),
                ),
                ("create_time", models.DateTimeField(null=True, verbose_name="建立时间")),
                ("TotalPosts", models.IntegerField(null=True, verbose_name="发帖数")),
            ],
        ),
        migrations.CreateModel(
            name="post",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("create_time", models.DateTimeField()),
                ("update_time", models.DateTimeField()),
                (
                    "tags",
                    models.CharField(max_length=100, null=True, verbose_name="标签"),
                ),
                (
                    "plate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.plate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.userinfo",
                    ),
                ),
            ],
        ),
    ]
