# Generated by Django 4.1 on 2024-04-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="managerInfo",
            fields=[
                (
                    "username",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="用户名",
                    ),
                ),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
                (
                    "gender",
                    models.CharField(max_length=1, null=True, verbose_name="性别"),
                ),
            ],
        ),
    ]
