# Generated by Django 4.1 on 2024-04-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_plate_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
