# Generated by Django 4.1 on 2024-04-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_post_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="create_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="update_time",
            field=models.DateTimeField(null=True),
        ),
    ]
