# Generated by Django 4.1 on 2024-04-28 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_uploadedfile_alter_post_create_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
    ]
