# Generated by Django 4.1 on 2024-05-17 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_post_image_alter_post_create_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="comment",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="managerInfo",
        ),
        migrations.DeleteModel(
            name="UploadedFile",
        ),
        migrations.RemoveField(
            model_name="post",
            name="update_time",
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="post/pic/", verbose_name="图片"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.post"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.userinfo"
            ),
        ),
    ]
