# Generated by Django 4.1 on 2024-05-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_comment_delete_managerinfo_delete_uploadedfile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="signature",
            field=models.TextField(null=True, verbose_name="签名"),
        ),
    ]
